fraud = [
    'bribes',
    'indicted',
    'guilty plea',
    'a misdemeanor',
    'tax offense',
    'verduisterd',
    'delict',
    'misbruik',
    'tegenprestatie',
    'delicten',
    'verdachte',
    'ambtelijke omkoping',
    'corrupt systeem'
    'corrupt',
    'smeergeld',
    'omkopen',
    'omkopers',
    'omgekochte ambtenaar',
    'omgekochte',
    'ambtelijke corruptie',
    'frauduleuze',
    'frauduleus',
    'verdenking',
    'schandaal',
    'voorarrest',
    'detentie',
    'passieve omkoping',
    'omkoping',
    'ambtsmisbruik',
    'verduistering',
    'corruptiezaak',
    'corruptie',
    'hoofdverdachte',
    'verdachte',
    'swindle',
    'federal prison',
    'oplichter',
    'ponzifraudeschandalen',
    'megafraudeur',
    'meesteroplichter',
    'fraud',
    'frauds',
    'fraudster',
    'investigation',
    'fraud investigation',
    'fraudulent',
    'cheat',
    'cheating',
    'swindling',
    'embezzlement',
    'deceit',
    'deception',
    'swindler',
    'bribery',
    'money laundering',
    'corruption',
    'conflict of interest',
    'detention',
    'illegal',
    'illicit',
    'plagiarism'
    'prosecution',
    'counterfeit',
    'adulteration'
    'tempering',
    'smuggling',
    'hoax',
    'deception',
    'fraudulence',
    'sham',
    'imposter',
    'dupery',
    'identity theft',
    'forgery',
    'guile',
    'perjury',
    'falsification',
    'scandal',
    'extortion',
    'recketeering',
    'misappropriation',
    'manipulation',
    'misconduct',
    'malfeasance',
    'charlatan',
    'delusive',
    'mislead',
    'subterfuge',
    'beguile',
    'bamboozle',
    'defraud',
    'delude',
    'delusion',
    'treacherous',
    'victimize',
    'fallacious',
    'circumvent',
    'investigate',
    'probe',
    'obstruction',
    'accused',
    'accusations',
    'negligence',
    'lawsuits',
    'misinform',
    'trail',
    'arrest',
    'collusion',
    'fixing',
    'allegedly',
    'suspicion',
    'breach',
    'slander',
    'pleaded guilty',
    'double deal'
    'double cross',
    'rip off',
    'false witness',
    'punitive damages',
    'malpractice',
    'kickback',
    'skimming',
    'overpayment',
    'overcharges',
    'tax evasion',
    'insider trading',
    'ponzi scheme',
    'pyramid scheme',
    'copyright infringement',
    'grand theft',
    'drug trafficking',
    'prison',
    'incarcerated',
    'arrest',
    'arrested',
    'profiteering',
    'overpaid',
    'victims',
    'ponzi scheme',
    'felony',
    'gevangenis',
    'witwassen',
    'verduisteren',
    'ponzi',
    'ponzi schemes',
    'pyramid scheme',
    'pyramid schemes',
    'stealing',
    'verdachte',
    'verdenkingen',
    'strafzaak',
    'verdachte',
    'strafbare handelingen',
    'steekpenningen',
    'beschuldigingen',
    'arrestatie',
    'corruptie',
    'ambtelijke corruptie',
    'verdacht',
    'mensensmokkel',
    'people smuggling',
    'human trafficking',
    'corrupte',
    'gevangenisstraf',
    'verdachten',
    'fraude',
    'fraudedelicten',
    'verduisterde',
    'financial fraud',
]

pep = [
    'politician',
    'vakminister',
    'vice-president',
    'campaña',
    'ambtenaar',
    'gobernantenan',
    'parlamentario',
    'directeur',
    'lijsttrekkersverkiezingen',
    'kieslijst',
    'meerderheidsfractie',
    'regeringen',
    'politieke systeem',
    'politieke',
    'parlementaire',
    'bewindsman',
    'vicepremier',
    'regerende',
    'kandidatenlijst',
    'stemmentrekker',
    'bewindslieden',
    'coalitieregeringen',
    'coalitieregering',
    'campagne',
    'fractie-collega',
    'ministerie',
    'ministeries',
    'staatssecretarissen',
    'staatssecretaris',
    'statenvoorzitter',
    'publiekstribune',
    'fractieleider',
    'polticus',
    'oudminister',
    'politieke arena',
    'bewindspersoon',
    'regeringspartij',
    'medeminister',
    'regerend politicus',
    'politiek bestuurder',
    'partijgenoot',
    'ministersploeg',
    'parliamentarians',
    'parliamentarian',
    'former minister',
    'staatshoofd',
    'oppositie',
    'formatieproces',
    'formateur',
    'oppositiepartij',
    'partij',
    'partijen',
    'rijksministerraad',
    'demissionair',
    'gouverneur',
    'parlement',
    'regering',
    'verkiezingen',
    'publiek geld',
    'ministerpresident',
    'ministers',
    'kandidaatminister',
    'kabinet',
    'premier',
    'premiers',
    'coalitiepartijen',
    'politico',
    'eleccion',
    'voto',
    'ministro',
    'oposicion',
    'parlamentario',
    'partido',
    'parlamento',
    'election',
    'minister',
    'exminister',
    'parliament',
    'lobbying',
    'government',
    'nepotism',
    'political',
    'head of state',
    'head of government',
    'senior politicians',
    'senior governement',
    'judicial official',
    'military official',
    'senior executive of state owned corporation',
    'political party official',
    'director',
    'deputy director',
    'politics',
    'governmental'
    'politician',
    'parliamentary',
    'public administration',
    'policy-making',
    'partisan',
    'economic',
    'policies',
    'political system',
    'presidency',
    'diplomatic',
    'coalition',
    'regime',
    'electoral',
    'politicized',
    'apolitical',
    'allegiance',
    'espionage',
    'opposition',
    'polices',
    'campaign',
    'petition',
    'taxation',
    'legislation',
    'debates',
    'politica',
    'politique',
    'populist',
    'reformist',
    'rhetorical',
    'societal',
    'prosecutorial',
    'bureaucratic',
    'congressional',
    'sectarian',
    'policymaker',
    'candidate',
    'governor',
    'democracies',
    'nationalist',
    'ombudsman',
    'interpol',
    'senate',
    'political party'
    'diplomat',
    'treasurer',
    'activism',
    'cabinet',
    'tax haven',
    'manifesto',
    'parliamentarian elections',
    'politieke functie',
    'politiek',
    'politicus',
    'public ministry',
    'ministry',
]

terror = [
    'criminele organisatie',
    'criminele',
    'illegale',
    'illegaal',
    'shooting',
    'wapenvergunning',
    'schutter',
    'schutters',
    'schoten',
    'beschieting',
    'schieten',
    'schietincident',
    'kartel',
    'drugskartel',
    'maffiabazen',
    'maffiabaas',
    'bolletjesslikkers',
    'uitbuiting',
    'exploitatie',
    'drugsmokkel',
    'drugsfabriek',
    'terrorism',
    'intimidation',
    'menace',
    'sword',
    'terror',
    'threat',
    'violence',
    'arm-twisting',
    'coercion',
    'compulsion',
    'constraint',
    'duress',
    'force',
    'pressure',
    'browbeating',
    'bulldozing',
    'bullying',
    'fear',
    'war'
    'ideology',
    'reign of terror',
    'insurgent',
    'extremism',
    'crime',
    'criminal',
    'separatism',
    'genocide',
    'racism',
    'treason',
    'bombing',
    'counterintelligence',
    'tyrannicide',
    'separatist',
    'vigilante',
    'rebellion',
    'abuses',
    'utilitarian',
    'proliferation',
    'condemned',
    'aphorism',
    'trafficking',
    'sanctions',
    'destruction',
    'threatening',
    'conspiracy',
    'zealot',
    'horror',
    'scourge',
    'extortion',
    'killing',
    'killed',
]
